---
- include: common.yml

# Here we are using the debian package if debian
- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: slave.yml
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

- include: deploy.yml
