---
# i.e. upgrade mesos, templates stay the same...
- name: Restart mesos-master
  shell: start mesos-master || restart mesos-master
  sudo: yes

- name: Restart mesos-slave 
  shell: start mesos-slave || restart mesos-slave
  sudo: yes

- name: Restart zookeeper
  shell: start zookeeper || restart zookeeper 
  sudo: yes
  when: ansible_os_family == "Debian"
